# Generated by Django 3.0.3 on 2020-05-14 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200514_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Full_payment',
            new_name='full_payment',
        ),
    ]
