# Generated by Django 3.0.3 on 2020-05-14 04:06

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200514_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='active',
            new_name='featured',
        ),
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.upload_location),
        ),
    ]
