# Generated by Django 3.0.3 on 2020-05-14 08:28

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200514_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.course_upload_location),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(null=True, upload_to=courses.models.upload_location),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('title', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('title', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('title', 'slug')},
        ),
    ]
