# Generated by Django 3.0.3 on 2020-05-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_free'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='free',
            new_name='paid',
        ),
    ]
