# Generated by Django 3.0.3 on 2020-05-16 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200515_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enroll_type',
        ),
    ]
