# Generated by Django 3.0.3 on 2020-05-21 08:00

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20200516_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.syllabus_upload_location),
        ),
    ]
